#!/bin/sh
ECHO=$(env which echo)
BUILDDIR="../../build"
FIRST_TIME=0
cd layers/openembedded-core
if [ ! -f ${BUILDDIR}/conf/local.conf ]; then
	FIRST_TIME=1
fi

. ./oe-init-build-env ${BUILDDIR}

echo ""
echo "NI ATE Core Configurations Gen 2 targets are:"
echo "    ateccgen2-minimal-image"
echo ""
echo "To build an image, execute: 'bitbake <supported_image_target>'"

if [ $FIRST_TIME -eq 1 ]; then
	mkdir -p conf
	cp ../layers/meta-ateccgen2/buildconf/*.conf conf/
	cat ../layers/meta-mender-community/templates/local.conf.append >> conf/local.conf
	cat ../layers/meta-mender-community/meta-mender-toradex-nxp/templates/local.conf.append  >> conf/local.conf
	sed -i 's/MENDER_STORAGE_TOTAL_SIZE_MB:apalis-imx8 = "2048"/MENDER_STORAGE_TOTAL_SIZE_MB:apalis-imx8 = "4096"/g' conf/local.conf
        sed -i 's/KERNEL_DEVICETREE:apalis-imx8 = "freescale\/imx8qm-apalis-v1.1-ixora-v1.2.dtb"/KERNEL_DEVICETREE:apalis-imx8 = "freescale\/imx8-apalis-smartracks.dtb"/g' conf/local.conf
	
	echo ""
	$ECHO -e "\033[1mA sample conf/local.conf file has been created"
	$ECHO -e "Check and edit the file to adapt to your local needs\033[0m"
fi
