#!/bin/sh
#
# Retain Dropbear SSH server service status
#

echo "$(mender show-artifact): Running $(basename "$0")" >&2

# Check current rootfs partition
current=$(mount | awk '$3 == "/" {print $1}')

# Deduce target rootfs partition based on current rootfs partition number
if [ $current = "/dev/mmcblk0p2" ]; then
    newroot=/dev/mmcblk0p3
elif [ $current = "/dev/mmcblk0p3" ]; then
    newroot=/dev/mmcblk0p2
else
    echo "Unexpected current root: $current" >&2
    exit 1
fi

mount $newroot /mnt

if [ $? -ne 0 ]; then
    echo "Failed to mount $newroot" >&2
    exit 1
fi

sleep 2

# Check that Dropbear socket symlink was created
# This indicates that Dropbear SSH server was enabled 
if [ -f /etc/systemd/system/sockets.target.wants/dropbear.socket  ]; then
    cp -P /etc/systemd/system/sockets.target.wants/dropbear.socket  /mnt/etc/systemd/system/sockets.target.wants/dropbear.socket 
    echo "Enabled Dropbear SSH server on new root partition" >&2
fi

umount $newroot
