#!/bin/sh
#
# Retain RCU user credentials from the current root
#

echo "$(mender show-artifact): Running $(basename "$0")" >&2

# Testing 
if [ ! -x /usr/bin/fw_printenv ]; then
    exit 1
fi

current=$(/usr/bin/fw_printenv mender_boot_part | awk -F = '{ print $2 }')

if [ $current = "2" ]; then
    newroot=/dev/mmcblk0p3
elif [ $current = "3" ]; then
    newroot=/dev/mmcblk0p2
else
    echo "Unexpected current root: $current" >&2
    exit 1
fi

mount $newroot /mnt

if [ $? -ne 0 ]; then
    echo "Failed to mount $newroot" >&2
    exit 1
fi

sleep 2

if [ -d /mnt/etc ]; then
    cp /etc/passwd /mnt/etc/passwd
    cp /etc/shadow /mnt/etc/shadow
    cp /etc/group /mnt/etc/group
    cp /etc/gshadow /mnt/etc/gshadow
    echo "Copied /etc/systemd/network to new root partition" >&2
else
    echo "Failed to find /etc on new root partition" >&2
    exit 1
fi

umount $newroot

