#!/bin/sh

# This script is responsible for reading the RCU serial number and setting the RCU hostname accordingly. Paired with avahi-daemon which enables mDNS, this provides an option for clients to communicate with the RCU just by knowing its serial number (instead of IP address).

hostname=null

# Try to grab custom hostname from .userconfig.json
if [ -f /data/rcu-service/config/.userconfig.json ]; then
    hostname=$(jq -r .SETTINGS[0].Hostname /data/rcu-service/config/.userconfig.json)
fi

# If custom hostname does not exist in JSON config file, try to grab RCU Carrier Module S/N from EEPROM
if [[ $hostname = null ]]; then

    # If RCU Carrier EEPROM is accessible and EEPROM revision is expected, verify RCU Carrier EEPROM checksum
    EEPROM_SYSFS_PATH=/sys/devices/platform/bus@56240000/56246000.i2c/i2c-*/*-0050/eeprom
    EEPROM_REV_REQ=1

    if [ -f $EEPROM_SYSFS_PATH  ] && [ $(hexdump -v -e '1/1 "%d"' $EEPROM_SYSFS_PATH -s 0 -n 1) = $EEPROM_REV_REQ ] ; then

        # EEPROM checksum stored at offset 1, total 4 bytes ( -s 1 -n 4 )
        EEPROM_CHECKSUM=$(printf "%d" 0x$(hexdump -v -e '1/1 "%02x"' $EEPROM_SYSFS_PATH -s 1 -n 4))

        # Generate CRC32 from EEPROM content, starting at offset 5, total 981 bytes ( -s 5 -n 981 )
        # 1 byte at offset 5 stores the number of datasets present in the EEPROM. The expected number of datasets in RCU Carrier EEPROM is 5.
        # Each dataset is 196 bytes in length. Hence, 1 + (196 * 5) = 981 bytes
        EEPROM_CRC32_GEN=$(python3 -c "import binascii; print(binascii.crc32(b'$(hexdump -v -e '1/1 "\x%02x"' $EEPROM_SYSFS_PATH -s 5 -n 981)'))")

        # If RCU Carrier EEPROM checksum is valid, read RCU Carrier Module S/N and form hostname
        if [ $EEPROM_CHECKSUM -eq $EEPROM_CRC32_GEN ]; then

            # RCU Carrier Module S/N stored at offset 412, total 4 bytes ( -s 412 -n 4)
            hostname="ni-rmx-1010x-"$(hexdump -v -e '1/1 "%02x"' $EEPROM_SYSFS_PATH -s 412 -n 4)
        else
            hostname="ni-rmx-1010x"
        fi
    else
        hostname="ni-rmx-1010x"
    fi
fi

if [ -f /usr/bin/hostnamectl ]; then
    /usr/bin/hostnamectl set-hostname ${hostname}
else
    hostname ${hostname}
fi
