#!/bin/sh

# This script is responsible for reading the RCU serial number and setting the RCU hostname accordingly. Paired with avahi-daemon which enables mDNS, this provides an option for clients to communicate with the RCU just by knowing its serial number (instead of IP address).

# Verify RCU Carrier EEPROM checksum
EEPROM_CHECKSUM=0x$(hexdump -v -e '1/1 "%02x"' /sys/devices/platform/bus@56240000/56246000.i2c/i2c-*/*-0050/eeprom -s 1 -n 4)
EEPROM_CRC32_GEN=$(python3 -c "import binascii; print(hex(binascii.crc32(b'$(hexdump -v -e '1/1 "\x%02x"' /sys/devices/platform/bus@56240000/56246000.i2c/i2c-*/*-0050/eeprom -s 5 -n 981)')))")

# Plan is to set hostname based on RCU Carrier S/N if EEPROM checksum is valid
if [ $EEPROM_CHECKSUM == $EEPROM_CRC32_GEN ]; then
    echo "EEPROM checksum valid!"
else
    echo "EEPROM checksum invalid"
fi

rcuserialpath=/usr/bin/rcu-serial
tdxserialpath=/proc/device-tree/serial-number

#set serial to Apalis SOM serial number
if [ -f ${tdxserialpath} ]; then
    serial=$(tr -d '\0' <${tdxserialpath})
fi

#if RCU serial number exists, we prefer the RCU serial number
if [ -f ${rcuserialpath} ]; then
    serial=$(tr -d '\0' <${rcuserialpath})
fi

#if serial number is still empty
if [ -z "$serial" -a "$serial" != " "  ]; then
    serial="EMPTYSERIAL"
fi

hostname="NI-SmartRacks-"${serial}

if [ -f /usr/bin/hostnamectl ]; then
    /usr/bin/hostnamectl set-hostname ${hostname}
else
    hostname ${hostname}
fi
