#!/bin/sh

rm /data/rcu-service/firmware/update-staged
rm /etc/rcu-mender-image-firstboot

RCU_SERVICE_STATUS=$(systemctl is-active rcu-service)
ETH0_STATUS=$(cat /sys/class/net/eth0/operstate)

if [ "$RCU_SERVICE_STATUS" = "active" ]; then
    mender commit
    touch /data/rcu-service/firmware/update-succeeded
    systemctl restart rcu-service
else
    mender rollback
    touch /data/rcu-service/firmware/update-failed
fi;
